reredux_config: "v006"
sim_type: "wombat"
psfs_in_file: True

global_seed: 2880

fitter_type: "max-ngmix-boot"
imageio_type: "meds-simp-sim"

fit_me_galaxy: False
fit_coadd_galaxy: True
use_coadd_prefix: False

model_nbrs: False
psf_ind_field: 'psf_id'

region: "weight"

min_weight: 1.0e-4

print_params: True

# find the center and reset the jacobians
pre_find_center: False

do_shear: False

psf_pars:
  model: 'gauss'
  ntry: 5
  fit_pars:
      maxfev: 2000

max_pars:
  method: 'lm'
  ntry: 2
  
  lm_pars:
    maxfev: 4000

replace_cov: False

round_pars:
  fitter_type: 'max'

use_logpars: True

model_pars:
  exp:
    g:
      type: "ba"
      sigma: 0.3

    T:
      type: "TwoSidedErf"
      pars: [-10.0, 1.0, 15.0, 1.0]

    counts:
      type: "TwoSidedErf"
      pars: [-10.0, 1.0, 15.0, 1.0]
      repeat: True

    cen:
      type: "dgauss"
      width: 0.27

# at bnl
time_per: 0.06

# all
nper: 10000

# checkpoint times in minutes, needed for condor in case we pass a batch system
# limit such as in the condor scavenge.
# 0 means after the first object

# checkpoints for lsf
checkpoints: [0,
              30,60,
              90,120, 
              150,180,
              210,240,
              270,300,
              330,360,
              390,420]
