reredux_config: "v1deep"

fitter_type: "max-ngmix-boot"
imageio_type: "meds-simp-sim"

fit_me_galaxy: False
fit_coadd_galaxy: True

model_nbrs: False
psf_ind_field: 'psf_id'


#region: "cweight-nearest"
region: "weight"

min_weight: 1.0e-4

# dummy field for the sims
#image_flags2check: 655343

use_psf_rerun: False
psf_rerun_version: "v8"

print_params: True

# find the center and reset the jacobians
pre_find_center: True

do_shear: False

psf_pars:
    model: 'em3'
    ntry: 20
    maxiter: 5000
    tol: 5.0e-6

max_pars:
    method: 'lm'
    ntry: 2
    
    lm_pars:
        maxfev: 4000

replace_cov: False

round_pars:
    fitter_type: 'max'


use_logpars: True
model_pars:
    exp:
        g_prior_type: "cosmos-sersic"

        # for asinh pars
        T_prior_type: "TwoSidedErf"
        T_prior_pars: [-10.0, 1.0, 15.0, 1.0]

        counts_prior_type: "TwoSidedErf"
        counts_prior_pars: [-10.0, 1.0, 15.0, 1.0]
        counts_prior_repeat: True

        cen_prior_type: "dgauss"
        cen_prior_pars: [0.27]

# more than double the time
time_per: 0.08

# all of them
nper: 1000


# checkpoint times in minutes, needed for condor in case we pass a batch system
# limit such as in the condor scavenge.
# 0 means after the first object

# checkpoints for lsf
checkpoints: [0,
              30,60,
              90,120, 
              150,180,
              210,240,
              270,300,
              330,360,
              390,420]
