reredux_config: "v004"
sim_type: "wombat"
psfs_in_file: True

reredux_githash: "9ce250ed9694e1949124490700021037e61daa85"
# metacalwcs branch
ngmix_githash: "b7b249c0197ea5af8071f44d9233a82b1fef8a10"
ngmixer_githash: "516f5c18ed6e34c85f037a5ba28841e1c433ca49"

global_seed: 32213

fitter_type: "metacal-ngmix-boot"
imageio_type: "meds-simp-sim"


fit_me_galaxy: False
fit_coadd_galaxy: True
use_coadd_prefix: False

model_nbrs: False
psf_ind_field: 'psf_id'

region: "weight"

min_weight: 1.0e-4

print_params: True

# find the center and reset the jacobians
#pre_find_center: True
pre_find_center: False

do_shear: False

psf_pars:
  model: 'gauss'
  ntry: 5

max_pars:
  method: 'lm'
  ntry: 2
  
  lm_pars:
    maxfev: 4000

replace_cov: False

round_pars:
  fitter_type: 'max'


metacal_pars:
  step: 0.01
  fixnoise: True
  rotnoise: True

use_logpars: True

model_pars:
  gauss:
    g:
      type: "ba"
      sigma: 0.3

    T:
      type: "TwoSidedErf"
      pars: [-10.0, 1.0, 15.0, 1.0]

    counts:
      type: "TwoSidedErf"
      pars: [-10.0, 1.0, 15.0, 1.0]
      repeat: True

    cen:
      type: "dgauss"
      width: 0.27

# longer for more complex wcs
time_per: 1.8

# all is 10000
nper: 1000

# checkpoint times in minutes, needed for condor in case we pass a batch system
# limit such as in the condor scavenge.
# 0 means after the first object

# checkpoints for lsf
checkpoints: [0,
              30,60,
              90,120, 
              150,180,
              210,240,
              270,300,
              330,360,
              390,420]
