# subtracting correlated noise
# gauss
reredux_config: "v14"
sim_type: "egret"

reredux_githash: "bf3db97f0b0b2708676de7a175102e9254e1c1bf"
# simobs branch
ngmix_githash: "3e4818f454c348728b005b52d1a9250f3da4063e"
# simobs branch
ngmixer_githash: "fb5d09ad51bb903a89c838022a8941aa0ad604f7"

global_seed: 30136
subn_nrand: 1
#extra_sim_noise: 0.152029
target_noise: 0.25

fitter_type: "metacal-subn-ngmix-boot"
imageio_type: "meds-simp-sim"

fit_me_galaxy: True
fit_coadd_galaxy: False

model_nbrs: False
psf_ind_field: 'psf_id'

region: "weight"

min_weight: 1.0e-4

print_params: True

# find the center and reset the jacobians
pre_find_center: False

do_shear: False

psf_pars:
  model: 'gauss'
  ntry: 5

max_pars:
  method: 'lm'
  ntry: 2
  
  lm_pars:
    maxfev: 4000

replace_cov: False

round_pars:
  fitter_type: 'max'


metacal_pars:
  step: 0.01

use_logpars: True

model_pars:
  gauss:
    g:
      type: "ba"
      sigma: 0.3

    T:
      type: "gmixnd"

      file: "${REREDUX_OUTPUTS_DIR}/max-v05d02/fitprior/max-v05d02-fitprior-log_T.fits"

      cov_factor: 1.44

    counts:
      type: "gmixnd"

      file: "${REREDUX_OUTPUTS_DIR}/max-v05d02/fitprior/max-v05d02-fitprior-log_F.fits"

      cov_factor: 1.44


    cen:
      type: "dgauss"
      width: 0.27

# doubled
time_per: 0.8

# all
nper: 5000

# checkpoint times in minutes, needed for condor in case we pass a batch system
# limit such as in the condor scavenge.
# 0 means after the first object

# checkpoints for lsf
checkpoints: [0,
              30,60,
              90,120, 
              150,180,
              210,240,
              270,300,
              330,360,
              390,420]
