# shallow data
reredux_config: "v11"

ngmix_githash: "38f7108a68919f77ae46631620ab7220e7e29c27"
reredux_githash: "cce8cd41d66c3a943d95b7a4b965de704ca852eb"
ngmixer_githash: "da8fa3b522fc4caeed6782b27644936b2974d15f"

global_seed: 18119

fitter_type: "metacal-ngmix-boot"
imageio_type: "meds-simp-sim"

fit_me_galaxy: True
fit_coadd_galaxy: False

model_nbrs: False
psf_ind_field: 'psf_id'

region: "weight"

min_weight: 1.0e-4

print_params: True

# find the center and reset the jacobians
pre_find_center: True

do_shear: False

psf_pars:
  model: 'em3'
  ntry: 20
  maxiter: 5000
  tol: 5.0e-6

max_pars:
  method: 'lm'
  ntry: 2
  
  lm_pars:
    maxfev: 4000

replace_cov: False

round_pars:
  fitter_type: 'max'


metacal_pars:
  step: 0.01

use_logpars: True

model_pars:
  exp:
    g:
      type: "ba"
      sigma: 0.3

    T:
      type: "gmixnd"

      # can re-use this, since this sim has the same exact configuration as v05b
      # ngauss=20 and logT range [-7,2]
      file: "${REREDUX_OUTPUTS_DIR}/max-v05d01/fitprior/max-v05d01-fitprior-log_T.fits"

      # 20% broader than fit prior (1.44=1.2**2)
      cov_factor: 1.44

    counts:
      type: "TwoSidedErf"
      pars: [-1.0, 1.0, 4.0, 1.0]
      repeat: True

    cen:
      type: "dgauss"
      width: 0.27

# more than double the time
#time_per: 1.2
# on comet
time_per: 0.8

# all
nper: 5000

# checkpoint times in minutes, needed for condor in case we pass a batch system
# limit such as in the condor scavenge.
# 0 means after the first object

# checkpoints for lsf
checkpoints: [0,
              30,60,
              90,120, 
              150,180,
              210,240,
              270,300,
              330,360,
              390,420]
