reredux_config: "v002"
sim_type: "wombat"
psfs_in_file: True

reredux_githash: ""
# simobs branch
ngmix_githash: ""
# simobs branch
ngmixer_githash: ""

global_seed: 10807

fitter_type: "metacal-detrend-ngmix-boot"
imageio_type: "meds-simp-sim"

# original noises vary:
#     mean is 0.062356718, min/max is 0.044916466/0.077410869
#
# this will be fairly high s/n
target_noise: 0.08

# factors from nsim
detrend_factors: [ 1.00714286,  1.01428571,  1.02142857 ]

fit_me_galaxy: False
fit_coadd_galaxy: True
use_coadd_prefix: False

model_nbrs: False
psf_ind_field: 'psf_id'

region: "weight"

min_weight: 1.0e-4

print_params: True

# find the center and reset the jacobians
#pre_find_center: True
pre_find_center: False

do_shear: False

psf_pars:
  #model: 'em2'
  model: 'gauss'
  ntry: 5
  #maxiter: 2000
  #tol: 5.0e-6

max_pars:
  method: 'lm'
  ntry: 2
  
  lm_pars:
    maxfev: 4000

replace_cov: False

round_pars:
  fitter_type: 'max'


metacal_pars:
  step: 0.01

use_logpars: True

model_pars:
  gauss:
    g:
      type: "ba"
      sigma: 0.3

    T:
      type: "gmixnd"

      file: "${REREDUX_OUTPUTS_DIR}/max-w002t01/fitprior/max-w002t01-fitprior-log_T.fits"
      cov_factor: 1.44

    counts:
      type: "gmixnd"

      file: "${REREDUX_OUTPUTS_DIR}/max-w002t01/fitprior/max-w002t01-fitprior-log_F.fits"
      cov_factor: 1.44

    cen:
      type: "dgauss"
      width: 0.27

time_per: 1.10

# all is 10000
nper: 2000

# checkpoint times in minutes, needed for condor in case we pass a batch system
# limit such as in the condor scavenge.
# 0 means after the first object

# checkpoints for lsf
checkpoints: [0,
              30,60,
              90,120, 
              150,180,
              210,240,
              270,300,
              330,360,
              390,420]
